//*****************************************************************************
//*****************************************************************************
//  FILENAME: Echo.h
//   Version: 2.5, Updated on 2013/5/19 at 10:42:30
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: Counter16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Echo_INCLUDE
#define Echo_INCLUDE

#include <m8c.h>

#pragma fastcall16 Echo_EnableInt
#pragma fastcall16 Echo_DisableInt
#pragma fastcall16 Echo_Start
#pragma fastcall16 Echo_Stop
#pragma fastcall16 Echo_wReadCounter              // Read  DR0
#pragma fastcall16 Echo_WritePeriod               // Write DR1
#pragma fastcall16 Echo_wReadCompareValue         // Read  DR2
#pragma fastcall16 Echo_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wEcho_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wEcho_ReadCompareValue         // Read  DR2 (Deprecated)

//-------------------------------------------------
// Prototypes of the Echo API.
//-------------------------------------------------
extern void Echo_EnableInt(void);                           // Proxy Class 1
extern void Echo_DisableInt(void);                          // Proxy Class 1
extern void Echo_Start(void);                               // Proxy Class 1
extern void Echo_Stop(void);                                // Proxy Class 1
extern WORD Echo_wReadCounter(void);                        // Proxy Class 2
extern void Echo_WritePeriod(WORD wPeriod);                 // Proxy Class 1
extern WORD Echo_wReadCompareValue(void);                   // Proxy Class 1
extern void Echo_WriteCompareValue(WORD wCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wEcho_ReadCounter(void);            // Deprecated
extern WORD wEcho_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for Echo API's.
//--------------------------------------------------

#define Echo_CONTROL_REG_START_BIT             ( 0x01 )
#define Echo_INT_REG_ADDR                      ( 0x0e1 )
#define Echo_INT_MASK                          ( 0x02 )


//--------------------------------------------------
// Constants for Echo user defined values
//--------------------------------------------------

#define Echo_PERIOD                            ( 0x0 )
#define Echo_COMPARE_VALUE                     ( 0x0 )


//-------------------------------------------------
// Register Addresses for Echo
//-------------------------------------------------

#pragma ioport  Echo_COUNTER_LSB_REG:   0x020              //DR0 Counter register LSB
BYTE            Echo_COUNTER_LSB_REG;
#pragma ioport  Echo_COUNTER_MSB_REG:   0x024              //DR0 Counter register MSB
BYTE            Echo_COUNTER_MSB_REG;
#pragma ioport  Echo_PERIOD_LSB_REG:    0x021              //DR1 Period register LSB
BYTE            Echo_PERIOD_LSB_REG;
#pragma ioport  Echo_PERIOD_MSB_REG:    0x025              //DR1 Period register MSB
BYTE            Echo_PERIOD_MSB_REG;
#pragma ioport  Echo_COMPARE_LSB_REG:   0x022              //DR2 Compare register LSB
BYTE            Echo_COMPARE_LSB_REG;
#pragma ioport  Echo_COMPARE_MSB_REG:   0x026              //DR2 Compare register MSB
BYTE            Echo_COMPARE_MSB_REG;
#pragma ioport  Echo_CONTROL_LSB_REG:   0x023              //Control register LSB
BYTE            Echo_CONTROL_LSB_REG;
#pragma ioport  Echo_CONTROL_MSB_REG:   0x027              //Control register MSB
BYTE            Echo_CONTROL_MSB_REG;
#pragma ioport  Echo_FUNC_LSB_REG:  0x120                  //Function register LSB
BYTE            Echo_FUNC_LSB_REG;
#pragma ioport  Echo_FUNC_MSB_REG:  0x124                  //Function register MSB
BYTE            Echo_FUNC_MSB_REG;
#pragma ioport  Echo_INPUT_LSB_REG: 0x121                  //Input register LSB
BYTE            Echo_INPUT_LSB_REG;
#pragma ioport  Echo_INPUT_MSB_REG: 0x125                  //Input register MSB
BYTE            Echo_INPUT_MSB_REG;
#pragma ioport  Echo_OUTPUT_LSB_REG:    0x122              //Output register LSB
BYTE            Echo_OUTPUT_LSB_REG;
#pragma ioport  Echo_OUTPUT_MSB_REG:    0x126              //Output register MSB
BYTE            Echo_OUTPUT_MSB_REG;
#pragma ioport  Echo_INT_REG:       0x0e1                  //Interrupt Mask Register
BYTE            Echo_INT_REG;


//-------------------------------------------------
// Echo Macro 'Functions'
//-------------------------------------------------

#define Echo_Start_M \
   ( Echo_CONTROL_LSB_REG |=  Echo_CONTROL_REG_START_BIT )

#define Echo_Stop_M  \
   ( Echo_CONTROL_LSB_REG &= ~Echo_CONTROL_REG_START_BIT )

#define Echo_EnableInt_M   \
   M8C_EnableIntMask(  Echo_INT_REG, Echo_INT_MASK )

#define Echo_DisableInt_M  \
   M8C_DisableIntMask( Echo_INT_REG, Echo_INT_MASK )

#endif
// end of file Echo.h
