//*****************************************************************************
//*****************************************************************************
//  FILENAME: TRIGG.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: TRIGG User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TRIGG_INCLUDE
#define TRIGG_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  TRIGG_Stop
#pragma fastcall16  TRIGG_Start
#pragma fastcall16  TRIGG_On
#pragma fastcall16  TRIGG_Off
#pragma fastcall16  TRIGG_Switch
#pragma fastcall16  TRIGG_Invert
#pragma fastcall16  TRIGG_GetState


//-------------------------------------------------
// Constants for TRIGG API's.
//-------------------------------------------------
//
#define  TRIGG_ON   1
#define  TRIGG_OFF  0

//-------------------------------------------------
// Prototypes of the TRIGG API.
//-------------------------------------------------
extern void  TRIGG_Start(void);                                     
extern void  TRIGG_Stop(void);                                      
extern void  TRIGG_On(void);                                      
extern void  TRIGG_Off(void);                                      
extern void  TRIGG_Switch(BYTE bSwitch);
extern void  TRIGG_Invert(void);                                         
extern BYTE  TRIGG_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
