//*****************************************************************************
//*****************************************************************************
//  FILENAME: I2CHW.h
//  Version: 2.00, Updated on 2013/5/19 at 10:43:40
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: UMName User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#ifndef I2CHW_SLAVE_INCLUDE
#define I2CHW_SLAVE_INCLUDE
#endif

#pragma fastcall16  I2CHW_Poll

#define I2CHW_CY8C22x45                            0                 // 1 if it is CY8C22x45 device, otherwice 0

#if I2CHW_CY8C22x45 
#pragma fastcall16  I2CHW_EnableHWAddrCheck
#pragma fastcall16  I2CHW_DisableHWAddrCheck
#endif

//-------------------------------------------------
// Status variables for I2CHW API's.
//-------------------------------------------------

//
//export only the count values used in the i/o processing routine
//

#define I2CHW_READ_BUFTYPE                   0x0
#define I2CHW_READ_FLASH                     I2CHW_READ_BUFTYPE & 0x01

extern unsigned char     I2CHW_Write_Count;

#if (I2CHW_READ_BUFTYPE)
extern unsigned int    I2CHW_Read_CountHI;

#endif
extern unsigned char    I2CHW_Read_Count;

//-------------------------------------------------
// Constants for I2CHW API's.
//-------------------------------------------------
//
#define I2CHW_SLAVE_ADDR                    0x30

extern char I2CHW_bStatus;
extern char I2CHW_RsrcStatus;

//definition of  I2CHW_Poll() if User Module parameter is configured as "Polled" 
//otherwise function is stubbed out.

extern void I2CHW_Poll(void);

#if I2CHW_CY8C22x45 
extern void  I2CHW_EnableHWAddrCheck(void);
extern void  I2CHW_DisableHWAddrCheck(void);
#endif
