//*****************************************************************************
//*****************************************************************************
//  FILENAME: VMT.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: VMT User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef VMT_INCLUDE
#define VMT_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  VMT_Stop
#pragma fastcall16  VMT_Start
#pragma fastcall16  VMT_On
#pragma fastcall16  VMT_Off
#pragma fastcall16  VMT_Switch
#pragma fastcall16  VMT_Invert
#pragma fastcall16  VMT_GetState


//-------------------------------------------------
// Constants for VMT API's.
//-------------------------------------------------
//
#define  VMT_ON   1
#define  VMT_OFF  0

//-------------------------------------------------
// Prototypes of the VMT API.
//-------------------------------------------------
extern void  VMT_Start(void);                                     
extern void  VMT_Stop(void);                                      
extern void  VMT_On(void);                                      
extern void  VMT_Off(void);                                      
extern void  VMT_Switch(BYTE bSwitch);
extern void  VMT_Invert(void);                                         
extern BYTE  VMT_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
