//*****************************************************************************
//*****************************************************************************
//  FILENAME: GYRO.h
//   Version: 2.00, Updated on 2013/5/19 at 10:43:43
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION:  I2Cm User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef GYRO_INCLUDE
#define GYRO_INCLUDE

#include <m8c.h>

// Create pragmas to support proper argument and return value passing
#pragma fastcall16  GYRO_fReadBytes
#pragma fastcall16  GYRO_bWriteBytes
#pragma fastcall16  GYRO_bWriteCBytes
#pragma fastcall16  GYRO_Start
#pragma fastcall16  GYRO_Stop
#pragma fastcall16  GYRO_fSendStart
#pragma fastcall16  GYRO_fSendRepeatStart
#pragma fastcall16  GYRO_SendStop
#pragma fastcall16  GYRO_fWrite
#pragma fastcall16  GYRO_bRead

//-------------------------------------------------
// Prototypes of the GYRO API.
//-------------------------------------------------
// High leval commands
extern void  GYRO_Start(void);
extern BYTE  GYRO_fReadBytes(BYTE bSlaveAddr, BYTE * pbXferData, BYTE bCnt, BYTE bMode);
extern BYTE  GYRO_bWriteBytes(BYTE bSlaveAddr, BYTE * pbXferData, BYTE bCnt, BYTE bMode);
extern BYTE  GYRO_bWriteCBytes(BYTE bSlaveAddr, const BYTE * pcbXferData, BYTE bCnt, BYTE bMode);
extern void  GYRO_Stop(void);

// Low level commands
extern BYTE  GYRO_fSendStart(BYTE bSlaveAddr, BYTE fRW);
extern BYTE  GYRO_fSendRepeatStart(BYTE bSlaveAddr, BYTE fRW);
extern void  GYRO_SendStop(void);
extern BYTE  GYRO_fWrite(BYTE bData);
extern BYTE  GYRO_bRead(BYTE fACK);

//-------------------------------------------------
// Constants for GYRO API's.
//-------------------------------------------------
#define GYRO_CompleteXfer   0x00 // Perform a complete I2C transfer
#define GYRO_RepStart       0x01 // Perform a complete transfer with a Repeat Start
#define GYRO_NoStop         0x02 // Perform a complete transfer, but leave off the stop

#define GYRO_READ           0x01 // Set the R/W flag after the slave address.
#define GYRO_WRITE          0x00 // Clear the R/W flag after the slave address.

#define GYRO_XFER_ERROR     0x00 // Communication error with the slave.
#define GYRO_NAKslave       0x00 // NAK the slave after a read.
#define GYRO_ACKslave       0x01 // ACK the slave after a read.

#endif
// end of file GYRO.h
