//*****************************************************************************
//*****************************************************************************
//  FILENAME: OME.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: OME User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef OME_INCLUDE
#define OME_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  OME_Stop
#pragma fastcall16  OME_Start
#pragma fastcall16  OME_On
#pragma fastcall16  OME_Off
#pragma fastcall16  OME_Switch
#pragma fastcall16  OME_Invert
#pragma fastcall16  OME_GetState


//-------------------------------------------------
// Constants for OME API's.
//-------------------------------------------------
//
#define  OME_ON   1
#define  OME_OFF  0

//-------------------------------------------------
// Prototypes of the OME API.
//-------------------------------------------------
extern void  OME_Start(void);                                     
extern void  OME_Stop(void);                                      
extern void  OME_On(void);                                      
extern void  OME_Off(void);                                      
extern void  OME_Switch(BYTE bSwitch);
extern void  OME_Invert(void);                                         
extern BYTE  OME_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
